project_name: gardener

builds:
  - 
    binary: bomber
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: bomber
    homepage: "https://github.com/devops-kung-fu/gardener"
    tap:
      owner: devops-kung-fu
      name: homebrew-tap
    commit_author:
      name: djschleen
      email: djschleen@gmail.com

checksum:
  name_template: 'checksums.txt'

nfpms:
  - 
    maintainer: DevOps Kung Fu Mafia <admin@dkfm.io>
    description: A utility that renders PlantUML diagram source in Markdown image tags.
    homepage: https://github.com/devops-kung-fu/gardener
    license: MPL
    formats:
      - deb
      - rpm

